ALTER TABLE `GuideProfile`
ADD COLUMN `adminReviewStatus` ENUM('PROFILE_INCOMPLETE', 'UNDER_REVIEW', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PROFILE_INCOMPLETE',
ADD COLUMN `adminReviewNotes` TEXT NULL,
ADD COLUMN `reviewSubmittedAt` DATETIME(3) NULL,
ADD COLUMN `reviewedAt` DATETIME(3) NULL,
ADD COLUMN `reviewedByUserId` VARCHAR(191) NULL;
